apiVersion: v1
kind: Pod
metadata:
  name: volum-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-extend
    volumeMounts:
    - mountPath: /test-volume
      name: extend-volume
  volumes:
  - name: extend-volume
    hostPath:
      path: /tmp/test_extend/
